### ISSUE TITLE
Error with "Datapacks" when loading world

### ISSUE THREAD

**Issue by noonononnonnoo** [DawnTeamMC/NookBuild#1]
![Annotation 2020-08-25 112504](https://user-images.githubusercontent.com/69599443/91201188-c23dd780-e6c5-11ea-9c6c-7952996af79b.png)
 This happens when I load the mod, and I know its this mod because when I remove it the problems disappear.

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed for the next version. (v1.0.1)
