### ISSUE TITLE
Flower piles outline?

### ISSUE THREAD

**Issue by nosevole** [DawnTeamMC/NookBuild#2]
Hello, absolutely love nookbuild, but the flower piles have white/black outlines. The leaf piles seem fine, but the flower piles look like maybe they were saved in the wrong format or something :-/ Not sure if that's a fault on my end or a bug? Thanks for your hard work, have a great day :) xxx

![2020-09-01_19 49 52](https://user-images.githubusercontent.com/68859697/91893705-70301f80-ec8c-11ea-94ec-d2404d19bf04.png)

**Comment by Hugman76** [comment]
I am just beyond stupid, thanks for the report! I will look into this once I get free time again

**Comment by nosevole** [comment]
Haha, absolutely no problem! Take care xxx

**Comment by Dhranios** [comment]
Seems flower piles are simply not setting the "allows transparent texture" value

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed for the next version.
