### ISSUE TITLE
Major problems with block tags

### ISSUE THREAD

**Issue by JuergenSchT** [DawnTeamMC/NookBuild#7]
Version 1.4.0 of NookBuild appears to have several errors regarding block tags for the new brick tiles blocks.
Server load stops after the errors are printed in the console. There is no crash report, [just the log](https://pastebin.com/WzyXc0GY).
The client does load to menu, but an absurdly larger number of errors are printed [in the client log](https://gist.github.com/JuergenSchT/f8025962472815272ea967efc41b4479). Then, when a world is selected (even one that did not have NookBuild in the past), a [error menu mentioning datapacks appears.](https://i.gyazo.com/c2f3d94e96bebce82de35cb384b7ccd7.png) Pressing "safe mode" does nothing. [This is what is printed in the client log](https://gist.github.com/JuergenSchT/cd50a981e0c164f41b03fd88f7e25ca7) (it gets repeated every time "safe mode" is pressed.

Versions involved:
- Minecraft: 1.16.5
- Fabric Loader: 0.11.1
- Fabric API: 0.30.0+1.16
- Dawn API: 1.6.3
- NookBuild: 1.4.0

**Comment by Hugman76** [comment]
Please use the latest Dawn API version (v1.6.5) and tell me if it still occurs.
Links:
> https://www.curseforge.com/minecraft/mc-mods/dawn/files/3192887
> https://modrinth.com/mod/dawn/version/YuE6MGlV

**Comment by JuergenSchT** [comment]
I tried singleplayer only [my server was busy], but the client and world do load normally, no errors printed in the console, too.

**Comment by Hugman76** [comment]
You've got to make sure everything has been updated to the latest version.

**Comment by JuergenSchT** [comment]
What I meant to say was that I updated Dawn API with the version you linked, and now everything works fine. I tested both singleplayer and multiplayer, no errors in the console and the blocks mentioned work fine as well.
